### ISSUE TITLE
/v1/register-application circular dependency problem for new application registration.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#10]
Following is the procedure to register a new application in registry office , 
1. v1/register-application service in registry office should be addressed by the new application.
2. In order to address this service , the new application requires the correct operation-key.
3. But It is not possible to obtain the correct operation key until a new application is provisioned within the micro service framework.

We have to check possible solutions to overcome this circular dependency problem.

**Comment by openBackhaul** [comment]
The registry-office :: /v1/register-application service shall not request for a proper operation-key value.
Instead registry-office shall be open for all registration attempts and assume to have received a deregistration request at the end of a time period (which can be configured as a Integer-Profile), if it didn't receive an approval message from the TypeApprovalRegister in meantime.

The security: apiKeyAuth: [] stereotype will be be removed from the registry-office :: /v1/register-application service with the next release of the specification.
