### ISSUE TITLE
/v1/list-applications and /v1/list-applications-in-generic-representation : OldRelease and NewRelease data to be removed

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#112]
As per conclusion made on issue https://github.com/openBackhaul/ApplicationPattern/issues/276, the services /v1/list-applications and /v1/list-applications-in-generic-representation need not contain data of OldRelease and NewRelease applications in the response-body.

Current implementation of /v1/list-applications and /v1/list-applications-in-generic-representation responds with the data of OldRelease and NewRelease applications which needs to be removed.

Similar issues:
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/56
https://github.com/openBackhaul/OamLog/issues/49
https://github.com/openBackhaul/AdministratorAdministration/issues/46

**Comment by PrathibaJee** [comment]
Issue is fixed in the PullRequest https://github.com/openBackhaul/RegistryOffice/pull/143. So closing this issue.
