### ISSUE TITLE
OperationUpdateBroadcast forwarding to be added with OUTPUT fc-port /v1/update-operation-client(ro-0-0-1-op-c-2022)

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#12]
The forwarding *OperationUpdateBroadcast* broadcasts the information about the backward compatible operations to the approved applications. 

In order to update the operations of Registry Office itself, the */v1/update-operation-client(ro-0-0-1-op-c-2022)* of RegistryOffice is also required to be added in the OUTPUT port of *OperationUpdateBroadcast* forwarding which is missing in the current load-file.

**Comment by openBackhaul** [comment]
**Decision:**
Forwarding table and LOADfile have to be completed in such a way that a /v1/update-operation-client with UUID = ro-0-0-1-op-c-2022 is point towards the RegistryOffice application itself.
