### ISSUE TITLE
Different TCP/IP addresses

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/RegistryOffice#168]
**Problem:**
Different TCP/IP addresses and protocols are used for addressing some application (TcpServer) from within or outside the GCP 'bubble'.

**Solution:**
- TcpServer definition to be completed by two additional fields (description, local-protocol) and there might be multiple TcpServer.
- TcpClient definition to be completed by an additional field (remote-protocol).

**Necessary Changes:**
**OAS:**
- [x] attributes and enumeration at 'tcp server' in control-construct:
- [x] attributes and enumeration at 'tcp server' in common-components
- [x] attribute and enumeration at 'tcp client' in control-construct:
- [x] attribute and enumeration at 'tcp client' in common-components
- [x] additional field in service body + examples:
  - [x] /v1/bequeath-your-data-and-die:
  - [x] PromptForBequeathingDataCausesNewApplicationBeingRequestedToInquireForApplicationTypeApprovals
  - [x] PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForDeregistrationNotifications
  - [x] PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForApprovalNotifications
  - [x] PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForWithdrawnApprovalNotifications
  - [x] PromptForBequeathingDataCausesTransferOfListOfAlreadyRegisteredApplications
  - [x] PromptForBequeathingDataCausesTARbeingRequestedToRedirectInfoAboutApprovalsToNewApplication
  - [x] PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement
  - [x] /v1/register-application
  - [x] TypeApprovalCausesRequestForEmbedding
  - [x] ServerReplacementBroadcast
  - [x] /v1/list-applications
  - [x] /v1/inquire-application-type-approvals
  - [x] /v1/notify-deregistrations
  - [x] /v1/notify-approvals
  - [x] ApprovalNotification
  - [x] /v1/notify-withdrawn-approvals
  - [x] /v1/relay-server-replacement

**CONFIGfile:**
- [x] Add description and protocol in existing instances of TcpServer
- [x] Create additional instance
- [x] Add protocol in existing instances of TcpClient

**Comment by PrathibaJee** [comment]
For the generic representation GUI , to populate the initial DropDown menu , we are calling the API "/v1/list-applications". 
From this API , Generic representation GUI will know the ip-address and port number of all the approved applications.
So in the ResponseBody of the API "/v1/list-applications" can we also add the protocol information ?
Kindly let us know your views.

**Proposal :**
Can we add the following changes to the OAS , 
- [ ] additional field in service ResponseBody + examples:
  - [ ] /v1/list-applications:

**Comment by openBackhaul** [comment]
Additional field in service ResponseBody + examples of /v1/list-applications added as proposed in [Comment above](https://github.com/openBackhaul/RegistryOffice/issues/168#issuecomment-1294508272).
