### ISSUE TITLE
reference attribute names to be changed in the callback URI for /v1/inquire-application-type-approvals :: RegistrationCausesInquiryForApplicationTypeApproval

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#18]
In callbacks section of */v1/inquire-application-type-approvals :: RegistrationCausesInquiryForApplicationTypeApproval* ,

Currently the reference attributes in the callback URI are subscriber-address, subscriber-port and subscriber-operation, but as per the attributes specified in the request.body, they needs to be updated as approval-application-address, approval-application-port and approval-operation.

Here,  https://{$request.body#subscriber-address}:{$request.body#subscriber-port}{$request.body#subscriber-operation} to be updated as 

_"https://{$request.body#approval-application-address}:{$request.body#approval-application-port}{$request.body#approval-operation}_"

**Comment by openBackhaul** [comment]
**Decision:**
Line 2032 with 
"https://{$request.body#subscriber-address}:{$request.body#subscriber-port}{$request.body#subscriber-operation}"
shall be changed to 
""https://{$request.body#approval-application-address}:{$request.body#approval-application-port}{$request.body#approval-operation}"

**Comment by IswaryaaS** [comment]
Same as the above scenario, In callback of _/v1/bequeath-your-data-and-die :: PromptForBequeathingDataCausesNewApplicationBeingRequestedToInquireForApplicationTypeApprovals :: requestBody :: properties_ of [RegistryOffice.yaml](https://github.com/openBackhaul/RegistryOffice/blob/develop/RegistryOffice.yaml), the attributes subscriber-address and subscriber-port needs needs to be updated as  approval-application-address and approval-application-port in

**Comment by openBackhaul** [comment]
In _RegistrationCausesInquiryForApplicationTypeApproval_ callback
changed from 
_https://{$request.body#subscriber-address/ip-address/ipv-4-address or request.body#subscriber-address/domain-name}:{$request.body#subscriber-port}{$request.body#subscriber-operation}:_
to
_https://{$request.body#approval-application-address/ip-address/ipv-4-address or request.body#approval-application-address/domain-name}:{$request.body#approval-application-port}{$request.body#approval-operation}:_

In _PromptForBequeathingDataCausesNewApplicationBeingRequestedToInquireForApplicationTypeApprovals_
attributes names have been corrected from 
_subscriber-address_ to _approval-application-address_
and from 
_subscriber-port_ to _approval-application-port_.
