### ISSUE TITLE
Making RegistryOffice to aware about the TLS information of the registered application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#186]
In the GenericRepresentationGUI(GRGUI) , we are populating the initial drop-down with the list of approved ApplicationNames. 
And on selecting an ApplicationName from this dropdown, GRGUI initiate “/v1/start-application-in-generic-representation” request to the selected application.

![image](https://user-images.githubusercontent.com/62344562/200014876-a40e3c1b-2069-453d-a45f-f8a3583c75a8.png)

To start the initial request “/v1/start-application-in-generic-representation”  ,  GRGUI gets the TCP details of the application from the service “/v1/list-applications” in RegistryOffice(RO).

Currently , RO have knowledge about the actual Ip-address and port of all the registered applications (**i.e. without TLS**).
In order to aware of the TCP details **with TLS** of all the registered application , following is one of the proposal , 

**How RO will know about the TCP details with TLS ?**
> [Assumption : NGINX IP address and proposed port shall be updated in the TCP server of the registering application]
- During new application registration , this information shall be included in the requestBody of the “/v1/register-application” , so that RegistryOffice will aware about the TLS details.

**What changes may be required in the /v1/list-applications API ?**
- In the /v1/list-application , we can include an optional requestBody  attribute called “application-protocol”. 
- If the “application-protocol” is provided with “https” , then all the application’s TCP details with TLS shall be shared. 
- From GRGUI , we can use the  filter “application-protocol=https” to receive the required information.

**Comment by openBackhaul** [comment]
Potential Proposal:
- AP://v1/register-yourself: to be changed from {own-protocol, own-address, own-port} to {http-address, http-port, https-address, https-port } (separate issue in the ApplicationPattern repository would be required).
-  In request body of RO://v1/register-application: application-protocol, application-address and application-port would be grouped into an object and there would be an array of this object.
- A protocol : ['HTTP,'HTTPS'] attribute to be added into all the requests asking for connection information as for example the RO://v1/list-application

**Comment by openBackhaul** [comment]
**Required Changes to the OAS:**
In requestBody of _RO://v1/register-application:_ :  
- _application-protocol_,_ application-address_ and _application-port_ shall be grouped into an object
- this object shall be item of an array
- required attributes shall be updated
- examples shall be updated

In requestBody of _RO://v1/list-applications_ :
- A _required-protocol_ attribute shall be added to the requestBody.
- The value of the _required-protocol_ shall be "from" the "remote-protocol" attribute in the TcpClient of the RO inside the GRGUI.
