### ISSUE TITLE
OAS : Request to remove “PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation” from the callback of /v1/bequeath-your-data-and-die 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#19]
This request is to remove “PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation” from the callback of /v1/bequeath-your-data-and-die (in OAS).
Kindly please let me know incase if my understanding is wrong.

In the specification of Registry Office, for /v1/bequeath-your-data-and-die service , we have the callback “PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation”.

**How this “PromptingNewReleaseForUpdatingServerCausesRequestForBroadcastingInfoAboutBackwardCompatibleUpdateOfOperation” forwarding-construct is being represented in load file?**
1. It’s an INVARIANT_PROCESS_SNIPPET
2. It will be executed for the operation-server “v1/update-client” and not for the service /v1/bequeath-your-data-and-die.
(Note : Also logically the old application will have no clue about the new operation versions , so this forwarding-construct representation is good)

**How and when this “BroadcastingInfoAboutBackwardCompatible” will happen then ?**
1. Before deregistering, the old application will RequestForBroadcastingInfoAboutServerReplacement to Registry Office. And Registry office will send  “v1/update-client” to all the applications including newly approved application.
2. As a part of v1/update-client, the details about the new version of the existing operations will be sent to registry office (via “v1/relay-operation-update) and registry office will broadcast the upgraded operation details to other applications.

Sharing the logic of /v1/update-client for our reference. Also kindly let me know if you have any comments on the same.

![image](https://user-images.githubusercontent.com/62344562/157286820-8763e8e8-cacf-4986-a7c1-de5acfee8fc9.png)

**Comment by openBackhaul** [comment]
Issue should affect the ApplicationPattern, too.
A second pull-request in the ApplicationPattern repository has been created.

**Comment by PrathibaJee** [comment]
Thanks for also fixing the problem in ApplicationPattern too. After seeing your comment , I had a check in other application's specification too. This change we have to include in other TAC applications aswell. So, created separate issue in other applications with a reference to this issue.
