### ISSUE TITLE
Update FakeIP addresses and Ports

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/RegistryOffice#259]
IP addresses and Ports to be updated according to [FakeIpList](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/TestingApplications/Infrastructure/SdnLaboratory/FakeAddresses/IpAddresses.md):
- ServiceList
- CONFIGfile
- OAS

**IP_1 and TCP_1 to be applied.**
**Release numbers to be regarded!**

**Comment by kmohr-soprasteria** [comment]
was basically already done.
Just found a mistake inside the oas, where there was a TAR 1-0-0 example with 2-0-0 ip/port.
