### ISSUE TITLE
Remove ApiSegment from UUIDs of HttpClients/Servers and TcpClients/Servers

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/RegistryOffice#266]
For simplification purposed, the ApiSegment shall be removed from UUIDs of HttpClients/Servers and TcpClients/Servers.
Example: _ro-2-0-0-http-c-**bm**-tar-1-0-0-000_ shall be changed into _ro-2-0-0-http-c-tar-1-0-0-000_

- Check [updated documentation about UUIDs](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md)
- Check [files of ApplicationPattern as a reference](https://github.com/openBackhaul/ApplicationPattern)
- Change ServiceList
- Change ProfileInstanceList
- Change CONFIGfile
- Change OAS

**Comment by kmohr-soprasteria** [comment]
mappings:  
```

http-c-bm-;http-c-
http-c-bs-;http-c-
http-c-im-;http-c-
http-c-is-;http-c-
tcp-c-bm-;tcp-c-
tcp-c-bs-;tcp-c-
tcp-c-im-;tcp-c-
tcp-c-is-;tcp-c-
http-s-bm-;http-s-
http-s-bs-;http-s-
http-s-im-;http-s-
http-s-is-;http-s-
tcp-s-bm-;tcp-s-
tcp-s-bs-;tcp-s-
tcp-s-im-;tcp-s-
tcp-s-is-;tcp-s-
-p-bm-;-p-
-p-bs-;-p-
-p-im-;-p-
-p-is-;-p-
-fd-bm-;-fd-
-fd-bs-;-fd-
-fd-im-;-fd-
-fd-is-;-fd-
-link-bm-;-link-
-link-bs-;-link-
-link-im-;-link-
-link-is-;-link-
```
