### ISSUE TITLE
ApprovalNotification INPUT fc-port requires a change

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#303]
Please find the attached [221213 ApprovalNotification_INPUTChange.docx](https://github.com/openBackhaul/RegistryOffice/files/10222562/221213.ApprovalNotification_INPUTChange.docx) that describes the scenario with example.
### Proposal :
To change the INPUT of the forwarding-construct “ApprovalNotification” from 
ro-2-0-0-op-s-is-003 (/v1/regard-updated-approval-status)
to 
ro-2-0-0-op-s-is-010 (/v1/relay-server-replacement)

Note :
This problem is observed for the applications that subscribed for “notify-approval” (lets say for the TAC applications except TAR)

### Problem :
Let’s take RO and EATL. RO is upgrading from version 1 to version 2.
Step 1 : EATL application has version 1.0.0 of RO
Step 2 : EATL receives request /v1/regard-application for “version 2.0.0” of RO and creates new LTP instance group
Step 3 : RO version 1.0.0 sends “v1/register-application” to RO version 2.0.0. So , RO version 2.0.0 sends /v1/embed-yourself to EATL which creates few more operation-clients and modifies the corresponding forwarding-constructs too.
Step 4 : RO version 1.0.0 sends “relay-server-replacement”. So , EATL will receive “v1/update-client” which updates the version 1.0.0 of RO to version 2.0.0.
        **Problem :** 
        1.	Two instances of the same application and version is now available in the CONFIGFile of EATL.
        2.	ForwardingConstruct mappings are scattered across both the application instances.
Step 5 : deregister application version 1.0.0 sends disregard-application for version 1.0.0. But version 1 will not be available , so no deletion happens.

### Solution :
This problem will occur in applications that subscribed for “notify-approval”. This problem shall be resolved by notifying the new application approval after the “relay-server-replacement” procedure.
Currently , after receiving an “approval” from “TAR” , RO sends “regard-application” to all the applications that subscribed for notification.
Changing the INPUT of the forwarding-construct “ApprovalNotification” 
from 
ro-2-0-0-op-s-is-003 (/v1/regard-updated-approval-status)
to 
ro-2-0-0-op-s-is-010 (/v1/relay-server-replacement)

Details as follow , 
Step 1 : EATL application has version 1.0.0 of RO
Step 2 : RO version 1.0.0 sends “v1/register-application” to RO version 2.0.0. So , RO version 2.0.0 sends /v1/embed-yourself to EATL which creates few more operation-clients and modifies the corresponding forwarding-constructs too.
Step 3 : RO version 1.0.0 sends “relay-server-replacement”. So , EATL will receive “v1/update-client” which updates the version 1.0.0 of RO to version 2.0.0.
Step 4 : RO sends "regard-application". Already version updated. But forwardings will be triggered as the service is idempotent.
Step 5 : If any operation gets upgraded,  new version sends  “relay-operation-update” which triggers “update-operation-client” to update the operation-name.
Step 6 : deregister application version 1.0.0 sends disregard-application for version 1.0.0. But version 1 will not be available , so no deletion happens.

**Comment by openBackhaul** [comment]
An excessive analysis of the problem has been made in a [comment in ALT issue#158](https://github.com/openBackhaul/ApplicationLayerTopology/issues/158#issuecomment-1356355522).

To double check, whether problem is solved with _/v1/update-client_ not to take effect, if application subscribed at _RO://v1/notify-approvals_.

**Comment by PrathibaJee** [comment]
First of all thanks for going through the high level steps and understanding the problem. 
Also thanks for the descriptive details of the /v1/update-client logic expectation.

From the table , could able to understand that 

> If already a http-client for a (application-name + new-release-number) is available ,  then 
> no need to perform any http-client update operation and only the linked tcp-client shall be updated. 

This will solve the problem of having two instance of the same application-name + release-number in the CONFIG file.
In this new proposal , we have to resolve one more problem(in a special scenario) to make the solution complete. Kindly please find the below details, 

So , after “update-client” , both the instance “http-client_1 with old release” and “http-client_2 with new release” will be available in the CONFIGfile. (The “http-client_1” will be deleted as a part of the “disregard-application”.)

**Problem :**
Similar to the https://github.com/openBackhaul/OperationKeyManagement/issues/141 issue , in the TAC applications EATL, OL , ALT , OKM  there are 3 operation-clients of RO which are not created based on a subscription. 
Please view this issue https://github.com/openBackhaul/ExecutionAndTraceLog/issues/155 for details.

In case , if an operation-client is not created from a subscription and is available in the CONFIGfile as a part of the initial deployment , 
then , 
we will lose these operation-clients once it is disregarded.

**For example :** 
in EATL’s CONFIGfile , 
while upgrading RegistryOffice to a newer version , 
RO's old version will have 8 operation-clients , 
whereas the new version will have only 4 operation-clients. 

When we disregard version 1 , 
their corresponding operation-clients will also be lost. (**highlighted in yellow in the below table**)
![image](https://user-images.githubusercontent.com/62344562/208321305-b06d9afc-a152-4ffa-94ee-404ab4402402.png)

**Proposal :**
**Proposal#1 :**
One proposal to solve this problem shall be adding individual subscription operations for creating operation-clients and fc-ports for this operations.

**Proposal#2 :**
In the server side , we can introduce a small logic to avoid losing such operation-clients , 
While receiving “update-client” , (the below flow chart only concentrates on the operation-client part)
![image](https://user-images.githubusercontent.com/62344562/208321322-c5f5e0a6-bfe8-4202-963b-fdb9bd44cb93.png)

**Comment by openBackhaul** [comment]
It seems we have the same discussion in two issues.
Please find my [comment in EATL issue#155](https://github.com/openBackhaul/ExecutionAndTraceLog/issues/155#issuecomment-1357592669)

**Comment by openBackhaul** [comment]
Issue will be solved by adding a description to _/v1/update-client_ in the ApplicationPattern ([AP issue#467](https://github.com/openBackhaul/ApplicationPattern/issues/467)).
