### ISSUE TITLE
Issue that could occur while changing an application's name and broadcasting to architecture

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#310]
Note : The problem statement documented in this issue will not affect currently, because there is no change expected for an application's name. This issue will occur only in a very rare case if name of an application is changing to a new name and it is trying to register to architecture. So, this issue need not be considered as priority for updating the specification though the solution is very simple. We can even deep dig into it in later release (may be in v3.0.0). 

Few points to be considered before entering into actual problem:
point 1.  The name of an application (http-server/application-name) can only be changed during release-upgrade. Which means, only when a new-release of an application is registering into the architecture, it has the possibility for changing it's own name. This is not possible to happen in run time. 
point 2: In current architecture, we can able to configure the updated application-name (http-client-interface-configuration/application-name) via OAM request. But, manually updating hundred(s) of application would be a hectic task and sometimes human error is possible . Kindly correct me if I am wrong. 
So, I have the following proposal for upgrading the application-name to newer name. 

Problem statement: 
- As per current architecture, upgrade process will work fine for NewRelease of an application having same application-name as current release. **_But, if the server/application-name is updated to a new name, the following might happen._**

![image](https://user-images.githubusercontent.com/88484011/208929172-f1f8ae73-0bbc-424f-a251-813d19151dd3.png)

Proposal:
- Adding a new attribute called "new-application-name" to request-body /v1/relay-server-replacement and /v1/update-client and modifying the existing attribute "application-name" to "old-application-name". 
- This attribute "new-application-name" shall have the value of updated application-name which is fetched from http-client/application-name of NewRelease after old-application receiving /v1/bequeath-your-data-and-die (which carries the new name in request-body)
- During the callback PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement, since, this attribute is present in request-body of /v1/update-client,
    -  the target application updates the value of newly created client instances (in case of TAC which already received /v1/regard-application and have two instances, old and new release of this application) 
    - or updates the old-application's application-name in case of other applications (which only have one instance for this application). 

![image](https://user-images.githubusercontent.com/88484011/208930160-70e75112-468b-4435-8d22-4efebdef4bd7.png)

**Comment by IswaryaaS** [comment]
The proposal would require very little modifications in OAS and server side implementation logic. 
This would not require any change to the existing config or forwarding file.

**Changes to be made in OAS files :**
1.	A new attribute shall be added “**new-application-name**”
Description: ‘from [/core-model-1-4:control-construct/logical-termination-point=\*-2-0-0-http-c-nr-\*-\*-\*-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name]'
2.	The old attribute can be modified from **“application-name” to “old-application-name”** 

_**The above changes to be made in :**_
1. In OAS  of [RegistryOffice](https://github.com/openBackhaul/RegistryOffice/blob/develop/spec/RegistryOffice.yaml):
    - /v1/relay-server-replacement 
    -  ServerReplacementBroadcast 
2. In OAS of [ApplicationPattern](https://github.com/openBackhaul/ApplicationPattern/blob/develop/ApplicationPattern.yaml):
    - /v1/update-client
        - Additionally, the description of /v1/update-client can be updated to complement old and new application name along with old and new release-number like 
    _“Initiates update of application-name/release number/TCP information at existing HttpClients and TcpClients if one HttpClient instance of old-application-name and old-release-number is present.
     If separate HttpClient and TcpClient instances are present for each of old-application-name/old-release-number and new-application-name/new-release-number, HttpClient with old-application-name and old-release-number shall not be updated, but OperationClients shall be transferred to the HttpClient with the new-application-name and new-release-number.”_
3. Common change in OAS of all applications
    - PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement

**Changes to be made in sever logic:**
The current implementation logic for /v1/update-client would require a very slight change. 

_Case 1:_ 
        - If the Config file contains distinct HttpClient instances for old-application-name/old-release-number and new-application-name/new-release-number, a check shall be included for both application-name and release-number. (before the check would be just made for same application-name and different release-numbers). The OperationClients shall be made to transferred to the HttpClient with the new-application-name and new-release-number 
       
_Case 2:_
      - If no HttpClient separate instance is present for new-application-name and we only have an HttpClient instance for old-application-name and old-release-number, the same old HttpClient and TcpClient can be updated with newer values present in request-body

**Comment by PrathibaJee** [comment]
Please consider one more impact of changing the application-name of an existing application. 

Once a new application gets approved by TAR , RO have to send embed-yourself to the new application.
In the request-body of embed-yourself  , RO have to send the following details , 
- old-release-protocol
- old-release-address
- old-release-port

If there is a change in the application-name of an application , then RO cannot able to find the correct old-release information.
![image](https://user-images.githubusercontent.com/62344562/209126425-18362199-2c79-4503-8b5d-a4fe7f112a76.png)

**Comment by PrathibaJee** [comment]
The proposal for the [initial problem](https://github.com/openBackhaul/RegistryOffice/issues/310#issue-1506403275) reported in the issue will be resolved in the [PR#312](https://github.com/openBackhaul/RegistryOffice/pull/312). 
So , issue shall be closed after merging that pull request.

A separate [issue](https://github.com/openBackhaul/RegistryOffice/issues/313) has been raised for the another problem mentioned in the [comment](https://github.com/openBackhaul/RegistryOffice/issues/310#issuecomment-1362736547).
