### ISSUE TITLE
Add old application name to /v1/register-yourself

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#313]
Root issue : https://github.com/openBackhaul/RegistryOffice/issues/310

Once a new application gets approved by TAR , RO have to send embed-yourself to the new application.
In the request-body of embed-yourself  , RO have to send the following details , 
- old-release-protocol
- old-release-address
- old-release-port

If there is a change in the application-name of an application , then RO cannot able to find the correct old-release information from it's config file.
![image](https://user-images.githubusercontent.com/62344562/209126687-d824045e-2f35-4f54-b265-6516c5c40744.png)

**Proposal :**
One possible solution could be including an attribute "old-application-name" and "old-release-number" to the request body of the following services
- /v1/register-yourself - In [ApplicationPattern OAS](https://github.com/openBackhaul/ApplicationPattern/blob/develop/ApplicationPattern.yaml) - required parameter
- /v1/register-application - In [RegistryOffice OAS](https://github.com/openBackhaul/RegistryOffice/blob/develop/spec/RegistryOffice%2Bforwardings.yaml) - optional parameter (can be avoided if http-server/application-name == OldRelease/http-client/application-name are same. 

Process explanation:
1. /v1/register-yourself is triggered with data of {old-application-name and old-release-number}.
   This data can be configured into HttpClient instance of OldRelease and can be further used for /v1/register-application. 
2. As a callback of /v1/register-yourself,,,, /v1/register-application will be triggered.
 In the request-body of register-application, we can include the attributes {old-application-name and old-release-number}
3. When RO receives /v1/register-application, along with creating new instances for new-application-name and new-release-number, we can create a mapping for HttpClient instance UUID of {old-application-name and old-release-number} to HttpClient instance UUID of  {new-application-name and new-release-number} can be stored in **appData** of RO. 

@PrathibaJee , thanks for finding out the issue.
Kindly let us know your views.
Note : creating this issue in RegistryOffice, once the proposal is accepted, we shall raise an issue in ApplicationPattern for updating specification of /v1/register-yourself in OAS.

**Comment by openBackhaul** [comment]
**Check adding optional attributes:**

- AP::OAS::/v1/register-yourself::current-application-name
- AP::OAS::/v1/register-yourself::current-release-number

- AP::OAS::PromptForRegisteringCausesRegistrationRequest::current-application-name
- AP::OAS::PromptForRegisteringCausesRegistrationRequest::current-release-number

- RO::OAS::/v1/register-application::current-application-name
- RO::OAS::/v1/register-application::current-release-number
