### ISSUE TITLE
api-segment in uuid of CurrentController/ tcp-c instance to be removed

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#351]
In Config file of [RegistryOffice](https://github.com/openBackhaul/RegistryOffice/blob/v2.0.1_spec/spec/RegistryOffice%2Bconfig.json), _ro-2-0-1-tcp-c-im-cc-1-0-0-000_ to be updated to _ro-2-0-1-tcp-c-cc-1-0-0-000_ where the api-segment "im" to be removed from uuid of tcp-client instance of CurrentController as well as in server-ltp list of http-c instance of CurrentController application.

**Comment by openBackhaul** [comment]
Corrected as wished and committed into ro_v2.0.2_spec .
