### ISSUE TITLE
register-application service is getting stuck when file-path is not present

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/RegistryOffice#370]
register-application service uses file-profile to fetch the file-path of the applicationData file .

When the fetched file-path is not available register-yourself service is getting stuck .

**Comment by PrathibaJee** [comment]
Issue is fixed as a part of https://github.com/openBackhaul/RegistryOffice/pull/371/files (related to changing the file path to correct format) and the other pull request in application pattern (https://github.com/openBackhaul/ApplicationPattern/issues/625). Hence closing this issue.
