### ISSUE TITLE
Implementation : File-path present in file-profile should be accessed with user-name,password and operation.

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/RegistryOffice#374]
Currently , In implementation , file-path is fetched from file-profile and we are trying to read or write into the file . 

But , We also have other attributes username , password, operation in file-profile which are applicable to file-path . 

Implementation to be updated such that while we are trying to access the file , if the username , password,operation field are present we have to access it with those particular permissions .

**Comment by PrathibaJee** [comment]
Shall we move this issue to Application pattern as this is a generic functionality. (Also please refer issue https://github.com/openBackhaul/ApplicationPattern/issues/641)

**Comment by PrathibaJee** [comment]
As per the decision in the issue https://github.com/openBackhaul/ApplicationPattern/issues/643 , we will not support the functionality to access file using credentials. So , closing this issue.
