### ISSUE TITLE
/v1/regard-updated-approval-status not triggering callback WithdrawnApprovalNotification for approval-status == REGISTERED

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#416]
As per current implementation, /v1/regard-updated-approval-status triggers WithdrawnApprovalNotification  only when approval-status == BARRED. 

- As per architecture, _a non-approved application shall not be present in any application other than RO. 
- This case of an application's approval-status changing from APPROVED to REGISTERED shall be considered as de-promotion. 
- This de-promotion shall be expected to be informed to other applications via **WithdrawnApprovalNotification** . 
- So other applications can remove this instance from their configuration._

In the above case, apart from informing to other applications, the following is expected to happen in RO
- ltp instances (http-c, tcp-c or any op-c or subscriptions ) need not be removed.
- fc-port need not to be removed from any subscriptions because, as per architecture even a non-registered application is allowed for subscribing to notifications
- fc-port to be removed from ServerReplacementBroadcast and OperationUpdateBroadcast. 
(Hope this is covered in https://github.com/openBackhaul/RegistryOffice/issues/409)

**Comment by PrathibaJee** [comment]
Issue merged as a part of this PR#431
