### ISSUE TITLE
Update the descriptions of property release-number from "update" to "find or update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#424]
In OAS, we have property release-number in services, which has descriptions like "update".
In very rare scenario, say if two instances of same application is available in config file and if an application is trying to subscribe for a service, it updates the first occurring instance of the client application instead of updating the already existing instance that matches for application-name and release-number.
This result in two instances (duplicate entries) of same application-name/release-number combination.

Proposal:
In order to avoid such cases, we can change the description of release-number property to "find or update" instead of "update" for following services.
- /v1/inquire-application-type-approvals

Related issue : https://github.com/openBackhaul/ApplicationPattern/issues/714

**Comment by PrathibaJee** [comment]
Similar issue , we discussed and decided in https://github.com/openBackhaul/ApplicationPattern/issues/714. The same solution shall be applied for this issue aswell for the services /v1/inquire-application-type-approvals.

**Comment by openBackhaul** [comment]
Changed as proposed from 'update' to 'find or update' in 
/v1/inquire-application-type-approvals :: approval-application-release-number
