### ISSUE TITLE
/v1/register-application :: application-data logic to be updated if preceding-data is not present in request-body

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#469]
In /v1/register-application service, if preceding-application-name and preceding-release-number attributes are not present, for the first request, only future-application-name and future-release-number are getting created in "preceeding-application-information" list. 

The same request for the second time is creating attributes preceding-application-name and preceding-release-number in "preceeding-application-information". This behavior is not expected. If preceding-data is not present in request-body, it shall not be created. 

On the other hand, if preceding-data is already present for an application in "preceeding-application-information" list, and if /v1/register-application is triggered for same application without preceding-data, then the available attributes shall be removed. This is currently not happening. 

>Priority:Medium;

**Comment by vanithavalluripalli9** [comment]
This issue is closed as part of PR https://github.com/openBackhaul/RegistryOffice/pull/498
