### ISSUE TITLE
/v1/register-application service implementation to be updated in test suite for protocol update. 

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/RegistryOffice#482]
In the test suite run the below mentioned test cases are failing : 

/v1/register-application::Attribute configured? / tcp-server-list updated? / protocol updated? : 

- Expected /core-model-1-4:control-construct
-  Check /core-model-1-4:control-construct

/v1/register-application::Update   LTP notified? / tcp-server-list update notified? / protocol update

-  Check /core-model-1-4:control-construct

**Problem Description :** 
In case of RO , as multiple tcp-clients are allowed , a new tcp-c will be formulated for HTTPS instead of replacing existing tcp-c instance while we are updating protocol from HTTP to HTTPS based on the tcp-server list.

So, in test suite while updating the protocol from HTTP to HTTPS , we have to check whether new instance of protocol is being created instead checking whether existing instance is only being updated.

**Similar Issue :** https://github.com/openBackhaul/ApplicationPattern/issues/806

**Comment by IswaryaaS** [comment]
As per https://github.com/openBackhaul/ApplicationPattern/issues/549#issuecomment-1741967061, only one tcp-client is allowed for an application. hence closing this issue. 
@vanithavalluripalli9 , kindly reopen the issue if my understanding is conflicting or create a new issue in impl (if not created) for this concept.
Thank you.
