### ISSUE TITLE
To remove unused APIs in the bequeath-your-data-and-die callbacks

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#528]
In the new specification , the following APIs are marked as deprecated and will not be available from 3.0.0,
- /v1/notify-deregistrations
- /v1/notify-approvals
- /v1/notify-withdrawn-approvals

And , in the bequeath-your-data-and-die callbacks , the following callbacks are removed , 
- PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForApprovalNotifications (for **/v1/notify-approvals**)
- PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForWithdrawnApprovalNotifications (for **/v1/notify-withdrawn-approvals**)

But , the following callback for **/v1/notify-deregistrations** is not removed,
- PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForDeregistrationNotifications

**Proposal :**

- The callback PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForDeregistrationNotifications shall be removed from both OAS and CONFIG file
- The new-release operation-client ro-2-1-0-op-c-im-nr-2-1-0-001 for the operation /v1/notify-deregistrations shall be removed from the CONFIG file

**Comment by openBackhaul** [comment]
Changed as proposed.

forwarding PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForDeregistrationNotifications has been deleted from
- ForwardingList
- CONFIGfile
- OAS

OperationClient to NewRelease://v1/notify-deregistrations has been deleted from
- ServiceList
- CONFIGfile
