### ISSUE TITLE
To remove unused operation-clients of NewRelease

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#529]
In the bequeath-your-data-and-die callbacks , the following callbacks are removed , 
- PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForApprovalNotifications (for /v1/notify-approvals)
- PromptForBequeathingDataCausesNewApplicationBeingRequestedToDocumentSubscriptionsForWithdrawnApprovalNotifications (for /v1/notify-withdrawn-approvals)

**Proposal :**
So , the following 2 operation-clients shall also be removed as they are unused,
- ro-2-1-0-op-c-im-nr-2-1-0-001 (/v1/notify-deregistrations)
- ro-2-1-0-op-c-im-nr-2-1-0-002 (/v1/notify-approvals)

**Comment by openBackhaul** [comment]
Both  
- ro-2-1-0-op-c-im-nr-2-1-0-001 (/v1/notify-deregistrations)
- ro-2-1-0-op-c-im-nr-2-1-0-002 (/v1/notify-approvals)

have been deleted from
- ServiceList
- CONFIGfile
