### ISSUE TITLE
To include operation-client for the uuid ro-2-1-0-op-c-im-tar-2-0-1-007 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#533]
The uuid ro-2-1-0-op-c-im-tar-2-0-1-007 is there in the ApprovingApplicationCausesResponding forwarding-construct.
But , in the operation-client stack of TypeApprovalRegister, there is no logical-termination-point instance available for this uuid.

**Proposal :** 
An operation-client instance shall be created for this callback url “/v1/document-embedding-status” and included to the TypeApprovalRegister application.

**Comment by openBackhaul** [comment]
Changed as proposed.
