### ISSUE TITLE
To remove the attributes of /v2/register-application from /v1/register-application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#535]
The API **/v1/register-application** is a deprecated and will be replaced by **/v2/register-application** from version 3.0.0.

In the currect OAS spec, for the API **/v1/register-application** one of the request-body **"new-single-TcpServer-format"** holds the attributes specified for the new API /v2/register-application.
This **new-single-TcpServer-format in /v1/register-application** consists of the following attributes , 
```
dispose-remainders-operation
preceding-release-operation
subsequent-release-operation
tcp-server (tcp-server-list changed to single instance)
```
This makes /v1/register-application as forward compatible.

**Proposal :**
Since we have a separate API /v2/register-application , shall we remove the
1. defined **"new-single-TcpServer-format"** from the **request-body of /v1/register-application** from OAS
2. example for the "new-single-TcpServer-format" from OAS
3. ro-2-1-0-op-s-is-001(/v1/register-application) from the management port of the following forwardings in CONFIG file,
      - **DeRegistrationBroadcast** (for the /v1/dispose-remainders-of-deregistered-application)
      - **ApprovingApplicationCausesPreparingTheEmbedding.RequestForOldRelease** (for the /v1/inform-about-preceding-release)
      - **ApprovingApplicationCausesPreparingTheEmbedding.RequestForUpdatingNewReleaseClient** (for the /v1/update-client-of-subsequent-release)

**Comment by openBackhaul** [comment]
Changed as proposed.
(The proposed changes make perfect sense, although I doubt that all the necessary adjustments have been taken into account.)
