### ISSUE TITLE
To include the new attributes preceding-release-operation, subsequent-release-operation in /v2/register-application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#536]
The request body of /v2/register-application missing the following attributes , 
```
- preceding-release-operation
- subsequent-release-operation
```

**Proposal :**
Requesting to add this attributes in the ,
1. properties 
2. required section
3. example 

of the request-body of /v2/register-application

**Comment by openBackhaul** [comment]
Changed as proposed.
