### ISSUE TITLE
To expand the wildcards in the output fc-port of the forwardings RequestForOldRelease RequestForUpdatingNewReleaseClient

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#537]
In the following forwarding , we have the output fc-ports defined in wildcards , 

1. **`ApprovingApplicationCausesPreparingTheEmbedding.RequestForOldRelease - ro-2-1-0-op-c-im-*-*-*-*-008`** (that refers the operation-client /v1/inform-about-preceding-release)
2. **`ApprovingApplicationCausesPreparingTheEmbedding.RequestForUpdatingNewReleaseClient - ro-2-1-0-op-c-im-*-*-*-*-009`** (that refers the operation-client /v1/update-client-of-subsequent-release)
3. **`ApprovingApplicationCausesPreparingTheEmbedding.RequestForEmbedding - ro-2-1-0-op-c-im-*-*-*-*-000`** (that refers the operation-client /v1/embed-yourself)

**Proposal :**
Instead of the wildcards , the actual uuids shall be included.

**Comment by openBackhaul** [comment]
Changed the ForwardingList and the CONFIGfile as proposed.
