### ISSUE TITLE
To replace the callback TypeApprovalCausesRequestForEmbedding with ApprovingApplicationCausesPreparingTheEmbedding.RequestForEmbedding

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#538]
In the version 2.1.0 of RegistryOffice, there is an embedding sequence.
In this embedding sequence ,  RequestForEmbedding(/v1/embed-yourself) will happen in the last.

**Proposal :**
Since we have the new forwarding ApprovingApplicationCausesPreparingTheEmbedding.RequestForEmbedding that will take care of the embeding of new application ,
 shall we **replace** the forwarding **TypeApprovalCausesRequestForEmbedding** with **ApprovingApplicationCausesPreparingTheEmbedding.RequestForEmbedding** in both OAS and CONFIG file.

**Comment by openBackhaul** [comment]
Both occurrences of TypeApprovalCausesRequestForEmbedding have been deleted from OAS, CONFIGfile and ForwardingList.
ApprovingApplicationCausesPreparingTheEmbedding.RequestForEmbedding has been updated according to the specification in AP://v1/embed-yourself.
