### ISSUE TITLE
To make the ApprovingApplicationCausesConnectingWith sequence backward compatible

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#540]
In the **version 2.1.0 of RegistryOffice**, there is an **ApprovingApplicationCausesConnectingWith** sequence.

This ApprovingApplicationCausesConnectingWith sequence will **work fine if all the TAC applications are >= version 2.1.0** and their /v1/regard-application API produces a response-body that consists of attribute "successfully-connected" that indicates the status of the connection.

This ApprovingApplicationCausesConnectingWith sequence **will not work , if any one of the TAC application is not < 2.1.0.**

**Proposal :**
Proposing the following to make this ApprovingApplicationCausesConnectingWith sequence backward compatible , 
1. If the response of **/v1/regard-application is 204** , that means , the **serving application is < 2.1.0**.
2. So , **for this RegistryOffice version 2.1.0** , we shall **skip** the steps in validating the response of /v1/regard-application if the **response-code is 204** and move to the next sequence.
3. Later in RegistryOffice **version 3.0.0** , we shall r**emove this exceptions**.

**Comment by openBackhaul** [comment]
I would rather prefer to keep the period of TAC applications being on different releases as short as possible (respectively, not to register any other new application during that period) than to introduce another if-then-else that later has to be removed again.

Would you see any significant disadvantage from this ignorant position?

**Comment by PrathibaJee** [comment]
Similar to the decision made in https://github.com/openBackhaul/RegistryOffice/issues/541#issuecomment-1908091299 , if there is a problem in the ApprovingApplicationCausesConnectingWith sequence , then that problem will be reported to TypeApprovalRegistry. After manually resolving the problem , manually the embedding status shall be updated by an administrator by using the new feature defined in the TAR issue [openBackhaul/TypeApprovalRegister#299](https://github.com/openBackhaul/TypeApprovalRegister/issues/299).
Hence closing this issue.
