### ISSUE TITLE
To include the new APIs to few legacy forwardings

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#545]
In the CONFIG file , the following operation-server shall be included as an input fc-port of the forwarding

**ServiceRequestCausesLoggingRequest,** 
ro-2-1-0-op-s-bm-013 - /v1/dispose-remainders-of-deregistered-application
ro-2-1-0-op-s-bm-014 - /v1/inform-about-preceding-release
ro-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release

**ServiceRequestCausesLtpUpdateRequest,**
ro-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release
ro-2-1-0-op-s-is-013 - /v1/notify-embedding-status-changes

**ServiceRequestCausesLtpDeletionRequest,**
ro-2-1-0-op-s-is-002 - /v1/deregister-application

**Comment by openBackhaul** [comment]
Services added as input in CONFIGfile and ServiceList.
