### ISSUE TITLE
To remove /v1/notify-embedding-status-changes from the management fc-port of few forwardings 

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#546]
As per our ApplicationPattern concept , management fc-port manages the creation or deletion of an output fc-port.

As per the specification , "ApplicationWhichWantsToGetNotifiedAboutEmbeddingStatusChanges" subscribes for the /v1/notify-embedding-status-changes. 

In the configuration file , this API /v1/notify-embedding-status-changes ro-2-1-0-op-s-is-013 is listed as a management port for the following forwardings , 

1. **TypeApprovalCausesRequestForEmbedding**
example output fcport : ro-2-1-0-op-c-im-tar-2-0-1-000(/v1/embed-yourself)

2. **ApprovingApplicationCausesPreparingTheEmbedding.RequestForOldRelease**
example output fcport : ro-2-1-0-op-c-im-*-*-*-*-008(/v1/inform-about-preceding-release)

3. **ApprovingApplicationCausesPreparingTheEmbedding.RequestForUpdatingNewReleaseClient**
example output fcport : ro-2-1-0-op-c-im-*-*-*-*-009(/v1/update-client-of-subsequent-release)

4. **ApprovingApplicationCausesPreparingTheEmbedding.RequestForEmbedding**
example output fcport : ro-2-1-0-op-c-im-*-*-*-*-000(/v1/embed-yourself)

**Proposal :**
SInce this service /v1/notify-embedding-status-changes will not initiate creating the ouput fc-ports for the above mentioned forwardings , it shall be removed from the management fc-ports.

> Related Issue : https://github.com/openBackhaul/RegistryOffice/issues/531

**Comment by openBackhaul** [comment]
1.:
Both occurrences of TypeApprovalCausesRequestForEmbedding have been deleted from OAS, CONFIGfile and ForwardingList according to [RO issue#538](https://github.com/openBackhaul/RegistryOffice/issues/538)
2. + 3. + 4.: 
RO://v1/notify-embedding-status-changes has been replaced by RO://v1/register-application as fc-port-update management in the ForwardingList. As management ports are listed just once in the CONFIGfile, no second fc-port got created for RO://v1/register-application, but the fc-port for RO://v1/notify-embedding-status-changes just removed.
