### ISSUE TITLE
Clarifications required in the RegistryOffice version 2.1.0 specification

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#547]
Kindly please clarify the following queries, clarifications, findings raised after analysing the RegistryOffice version 2.1.0 specification, 
Also please correct if any of the understand is wrong.
Many thanks.

### /v1/bequeath-your-data-and-die 
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/528
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/529
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/530
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/534

### /v1/notify-embedding-status-changes
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/531
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/546

### register-application
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/535
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/536

### Related to the callback ApprovingApplicationCausesPreparingTheEmbedding
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/538
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/544
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/541
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/537
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/527

### Related to the callback ApprovingApplicationCausesConnectingWith
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/539
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/540
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/543

### /v1/regard-updated-approval-status
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/542
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/532
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/533

### legacy forwardings
- [ ] https://github.com/openBackhaul/RegistryOffice/issues/545

**Comment by openBackhaul** [comment]
All issue closed.
