### ISSUE TITLE
ro-2-1-0-op-s-is-013 to be added to INPUT fc-port of ServiceRequestCausesFcUpdateRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#561]
Since, ro-2-1-0-op-s-is-013 /v1/notify-embedding-status-changes creates an OUTPUT fc-port in EmbeddingStatusNotification (which is a subscription forwarding-construct), this service is eligible for sending notification to ALT as a part of fc-port update. 

So, this operation-server shall be added to _ServiceRequestCausesFcUpdateRequest_. 

This shall be added to config.json and forwardings.yaml files

**Comment by openBackhaul** [comment]
Changed as proposed.
