### ISSUE TITLE
Update file-path attribute to file-name

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#564]
As per decision made on https://github.com/openBackhaul/ApplicationPattern/issues/646#issuecomment-1508192091, the attribute file-path in file-profile instances shall be updated as file-name under file-profile-configuration.

Also, the attributes "user-name" and "password" shall be removed from file-profile-1-0:file-profile-pac/file-profile-configuration.

Update shall be made in 
-  config.json
- profileInstances.yaml
- profiles.yaml

**Comment by openBackhaul** [comment]
Covered in pull-request #602
