### ISSUE TITLE
ro-2-1-0-op-s-is-003 shall be included in INPUT fc-port list of ServiceRequestCausesLtpUpdateRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#567]
- /v1/regard-updated-approval-status (ro-2-1-0-op-s-is-003) is responsible for updating operation-client LTP instance as per the forwarding ApprovingApplicationCausesResponding (i.e. it updates the response-receiver-operation which is incoming in request-body).
- So, it shall be included in INPUT fc-port of ServiceRequestCausesLtpUpdateRequest forwarding, so that this change in LTP could be notified to ALT. 
- This change shall be updated in config.json and forwardings.yaml files

**Comment by openBackhaul** [comment]
Corrected as proposed.
