### ISSUE TITLE
ForwardingKind of ro-2-1-0-op-fc-is-042 and ro-2-1-0-op-fc-is-044 shall be updated to PROCESS_SNIPPET

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#568]
The "ForwardingKind" value of the following forwarding-constructs are given as "INVARIANT_PROCESS_SNIPPET" . But they actually shall be "PROCESS_SNIPPET". 
- ro-2-1-0-op-fc-is-042 - ApprovingApplicationCausesPreparingTheEmbedding.RequestForOldRelease
- ro-2-1-0-op-fc-is-044 - ApprovingApplicationCausesPreparingTheEmbedding.RequestForUpdatingNewReleaseClient

This value shall be changed to PROCESS_SNIPPET

**Comment by openBackhaul** [comment]
Corrected as proposed.
