### ISSUE TITLE
server-ltp uuid of operation-clients of /v1/inform-about-preceding-release and /v1/update-client-of-subsequent-release of all client applications shall be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#569]
In **config.json** file, the operation-client instances of /v1/inform-about-preceding-release and /v1/update-client-of-subsequent-release of all applications has been given as http-c of OKM (ro-2-1-0-http-c-okm-2-0-1-000 ) instead of the corresponding http-client uuid. 

For example, 
In "ro-2-1-0-op-c-im-ro-2-0-1-008" and "ro-2-1-0-op-c-im-ro-2-0-1-009", the server-ltp list value shall be updated with **_ro-2-1-0-http-c-ro-2-0-1-000_** instead of ro-2-1-0-http-c-okm-2-0-1-000. 

Similarly, the op-c instances for /v1/inform-about-preceding-release and /v1/update-client-of-subsequent-release for all applications shall be updated to corresponding http-client uuid.

**Comment by openBackhaul** [comment]
Corrected as proposed.
