### ISSUE TITLE
Registry Office implementation : approval-application attribute update for the value TypeApprovalRegister

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#73]
In Registry office  for a service , - /v1/inquire-application-type-approvals (approval-application = TypeApprovalRegister) 

Due to an expected update in specification for the services where the description of application-name attribute to be changed from "find or create" to "find" for the actual application involved, the implementation needs an update.

 [Related Issue : #92](https://github.com/openBackhaul/ApplicationPattern/issues/92)

**Comment by PrathibaJee** [comment]
Incorporated the request in the pull request #84 . So , the /v1/inquire-application-type-approvals will be processed by the server if and only if the incoming application-name is equal to the application-name in the uuid "ro-0-0-1-http-c-2030". 
Note : This feature is not part of the current specification , but this will prevent the current server implementation too to not fall into wrong forwardings.
