### ISSUE TITLE
How to identify and separate application data for the Registry office application?

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#82]
This quesiton is a child to the [ApplicationPattern/Issue#105](https://github.com/openBackhaul/ApplicationPattern/issues/105)

Separating application data from load file requires further investigation on the application specific scenarios.

1. For Type approval application , we can remove the application-profile from the load file. It is straight forward.
2. But for Registry office application,
      -  We are storing the registered application in the LTP itself (this is for a reason , as we have to further contact that application to perform embed-yourself, update-client , update-operation-client)
      -   If 30 applications registers in RO , for all the registrations,  LTPs and fc-ports will be added in the load file.
      -   This LTPs and fc-ports added to the load file are actually RO’s application data.

**Whether we have to consider this as application data ?**
If so , can we maintain this data specific to the application in a separate file ?

1. Can we keep only the following in the configuration file ,
      - basic services related configuration 
      - the application specific invariant forwardings (for example , for TAR it sends approval to RO which is an invariant forwarding and known during the definition of the application)
 2. Can we keep another file , 
     - that maintains the registered application information
     - the subscription fc-ports
     - in the ONF format

**Comment by openBackhaul** [comment]
LTPs, FCs, FcPorts ... are representing configuration information, particularly if they are required for formulation requests to the respective applications.
Because we haven't had any Profile definitions before splitting up into CONFIGfile and DATAfile, it's rather unlikely that we have any information to be stored in a separate DATAfile.
@PrathibaJee: If you could live with this result, please feel free closing the issue. 
Otherwise, please describe your doubts.

**Comment by PrathibaJee** [comment]
Yes , since we are not going to store application specific data in the profiles(apart from the concepts we introduced for generic representation) , we may not require a APPDATAFile. Closing this issue. Thanks.
