### ISSUE TITLE
Load file: ServerReplacementBroadcast/OperationUpdateBroadcast: Need to remove the management fc-port for the operation-server /v1/register-application

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/RegistryOffice#9]
As a part of **/v1/register-application**, we create **fc-port** only for the forwarding-construct "**TypeApprovalCausesRequestForEmbedding**". And for "**ServerReplacementBroadcast**" , "**OperationUpdateBroadcast**" we will create fc-ports only on **receiving an approval from the TAR** application.
Could you please kindly remove the management fc-ports listed for the operation-server /v1/register-application(ro-0-0-1-op-s-3001) from "ServerReplacementBroadcast" , "OperationUpdateBroadcast"  FCs.
Kindly let me know your view.

**Comment by openBackhaul** [comment]
The follow two FC have to be changed:
- op-fc-3009
  - ltp op-s-3001 has to be removed
  - ltp op-s-3002 has to get a proper local-id

- op-fc-3010
  - ltp op-s-3001 has to be removed
  - ltp op-s-3002 has to get a proper local-id

**Comment by openBackhaul** [comment]
Changed as proposed in [Comment above](https://github.com/openBackhaul/RegistryOffice/issues/9#issuecomment-1165517118).
