### ISSUE TITLE
OAS : /v1/bequeath-your-data-and-die : callback : reference path needs update

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/RegistryOffice#91]
Error description:
In callback "_PromptForBequeathingDataCausesTARbeingRequestedToRedirectInfoAboutApprovalsToNewApplication_", we have request-body attribute "_subscriber-operation_", the reference path under description of the attribute needs an update. The path is intended to refer an operation-server ltp (ro-0-0-1-op-s-3003), but the proceeding path points to operation-client.

Possible solution:
In the description, path needs an update to point to _operation-server-interface-capability/operation-name_ as below.

Here, the current description contains /core-model-1-4:control-construct/logical-termination-point=_ro-0-0-1-op-s-3003_/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name,
which actually would be 
/core-model-1-4:control-construct/logical-termination-point=ro-0-0-1-op-s-3003/layer-protocol=0/**operation-server-interface-1-0:operation-server-interface-pac/operation-server-interface-capability/operation-name**

Note: ro-0-0-1-op-s-3003 refers to /v1/regard-updated-approval-status

Related issues:
https://github.com/openBackhaul/TypeApprovalRegister/issues/40
https://github.com/openBackhaul/ExecutionAndTraceLog/issues/41
https://github.com/openBackhaul/OamLog/issues/38
https://github.com/openBackhaul/AdministratorAdministration/issues/37
https://github.com/openBackhaul/ApplicationLayerTopology/issues/60
https://github.com/openBackhaul/OperationKeyManagement/issues/28

**Comment by openBackhaul** [comment]
Line 638 UUID is pointing to server, but path in data tree is pointing to client.
Data tree statement has to be corrected from operation-client to operation-server.

**Comment by openBackhaul** [comment]
Changed as proposed in very nice issue description.
Directly pushed into develop.

**Comment by openBackhaul** [comment]
UPDATE 29th of November 2022:
In general:
Some callback is describing a request, which is sent by the application.
This cannot be described by an own OperationServer, but must be a OperationClient.

In regards with PromptForBequeathingDataCausesTARbeingRequestedToRedirectInfoAboutApprovalsToNewApplication Reference of operation-name has been changed towards: _/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-im-tar-1-0-0-005/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name_

This change has been made during solving another issue.
